package game

// Generated by: pktdiff -gen-test 1001 java-20260929-130607.log ready
// Java run of quest 1001 recorded with the real 1.9 client: the last session of the log, 18 steps. Each step is a
// client action; Want is what the Java server answered. Regenerate rather than hand-edit the Want lists; add
// hand-written checks in a separate test.
// Looted but not granted (pass -items to grant quest items): 167000230, 169000003, 182400001, 113300558, 182003943, 167000228.

import "testing"

func TestQuest1001JavaReplay(t *testing.T) {
	f := newReplayFixture(t, 1001, replayQuest{ID: 1001, Status: "START", Vars: 0})
	f.run([]replayStep{
		{Name: "click npc 203071", Kind: "click", NPC: 203071, Want: replayWant{Windows: [][2]int32{{10, 0}}}},
		{Name: "select dialog 25 quest 1001 on npc 203071", Kind: "select", NPC: 203071, Dialog: 25, Quest: 1001, Want: replayWant{Windows: [][2]int32{{1011, 1001}}}},
		{Name: "select dialog 1012 quest 1001 on npc 203071", Kind: "select", NPC: 203071, Dialog: 1012, Quest: 1001, Want: replayWant{Windows: [][2]int32{{1012, 1001}}, Movies: []uint16{15}}},
		{Name: "movie 15 ended", Kind: "movie", Movie: 15},
		{Name: "select dialog 1013 quest 1001 on npc 203071", Kind: "select", NPC: 203071, Dialog: 1013, Quest: 1001, Want: replayWant{Windows: [][2]int32{{1013, 1001}}}},
		{Name: "select dialog 10000 quest 1001 on npc 203071", Kind: "select", NPC: 203071, Dialog: 10000, Quest: 1001, Want: replayWant{Windows: [][2]int32{{10, 0}}, Quests: []replayQuest{{Action: 2, ID: 1001, Status: "START", Vars: 1}}}},
		{Name: "kill npc 210670", Kind: "kill", NPC: 210670, Want: replayWant{Quests: []replayQuest{{Action: 2, ID: 1001, Status: "START", Vars: 2}}}},
		{Name: "kill npc 210670", Kind: "kill", NPC: 210670, Want: replayWant{Quests: []replayQuest{{Action: 2, ID: 1001, Status: "START", Vars: 3}}}},
		{Name: "kill npc 210670", Kind: "kill", NPC: 210670, Want: replayWant{Quests: []replayQuest{{Action: 2, ID: 1001, Status: "START", Vars: 4}}}},
		{Name: "kill npc 210670", Kind: "kill", NPC: 210670, Want: replayWant{Quests: []replayQuest{{Action: 2, ID: 1001, Status: "START", Vars: 5}}}},
		{Name: "kill npc 210670", Kind: "kill", NPC: 210670, Want: replayWant{Quests: []replayQuest{{Action: 2, ID: 1001, Status: "START", Vars: 6}}}},
		{Name: "click npc 203071", Kind: "click", NPC: 203071, Want: replayWant{Windows: [][2]int32{{10, 0}}}},
		{Name: "select dialog 25 quest 1001 on npc 203071", Kind: "select", NPC: 203071, Dialog: 25, Quest: 1001, Want: replayWant{Windows: [][2]int32{{1352, 1001}}}},
		{Name: "select dialog 1353 quest 1001 on npc 203071", Kind: "select", NPC: 203071, Dialog: 1353, Quest: 1001, Want: replayWant{Windows: [][2]int32{{1353, 1001}}}},
		{Name: "select dialog 1354 quest 1001 on npc 203071", Kind: "select", NPC: 203071, Dialog: 1354, Quest: 1001, Want: replayWant{Windows: [][2]int32{{1354, 1001}}}},
		{Name: "select dialog 10001 quest 1001 on npc 203071", Kind: "select", NPC: 203071, Dialog: 10001, Quest: 1001, Want: replayWant{Windows: [][2]int32{{10, 0}}, Quests: []replayQuest{{Action: 2, ID: 1001, Status: "START", Vars: 7}}}},
		{Name: "select dialog 25 quest 1001 on npc 203071", Kind: "select", NPC: 203071, Dialog: 25, Quest: 1001, Want: replayWant{Windows: [][2]int32{{1693, 1001}}}},
		{Name: "select dialog 33 quest 1001 on npc 203071", Kind: "select", NPC: 203071, Dialog: 33, Quest: 1001, Want: replayWant{Windows: [][2]int32{{1779, 1001}}}},
	})
}
