package game

// questLevelUp dispatches Java QuestEngine.onLvlUp. QuestService calls it
// after quest completion as well as when the character actually levels up.
func (c *conn) questLevelUp() {
	if c == nil || c.player == nil {
		return
	}
	c.kerubThreatLevelUp()
	c.thinkingAheadLevelUp()
	c.requestOfTheElimLevelUp()
	c.illegalLoggingLevelUp()
	c.wheresRaeLevelUp()
	c.treasureOfTheDeceasedLevelUp()
	c.neutralizingOdiumLevelUp()
	c.dukakiOdiumLevelUp()
	c.dangerFromAboveLevelUp()
	c.maskedLoiterersLevelUp()
	c.huntingLepharistRevolutionariesLevelUp()
	c.frillneckHuntLevelUp()
	c.forestOutlawLevelUp()
	c.sourcePollutionLevelUp()
	c.heldSacredLevelUp()
	c.mandurisSecretLevelUp()
	c.rulersDutyLevelUp()
	c.satalocasHeartLevelUp()
	c.disappearingAetherLevelUp()
	c.refreshingSpringsLevelUp()
	c.kaidanPrisonerLevelUp()
	c.secretsOfTempleLevelUp()
	c.shadowsCommandLevelUp()
	c.somethingInTheWaterLevelUp()
	c.scoutingTheScoutsLevelUp()
	c.dangerousArtifactLevelUp()
	c.keeperKaidanKeyLevelUp()
	c.balaurConspiracyLevelUp()
	c.rootOfRotLevelUp()
	c.ruinsOfRoahLevelUp()
	c.klawThreatLevelUp()
	c.powerOfElimLevelUp()
	c.eternalRestLevelUp()
	c.lepharistPoisonResearchLevelUp()
	c.creatingMonsterLevelUp()
	c.archonOfStormsLevelUp()
	c.indratuLegionLevelUp()
	c.abyssTrainingLevelUp()
	c.speakingBalaurLevelUp()
	c.newWingsLevelUp()
	c.josnackDilemmaLevelUp()
	c.fragmentOfMemory2LevelUp()
	c.aetherInsanityLevelUp()
	c.markOfVengeanceLevelUp()
	c.flyingReconnaissanceLevelUp()
	c.trandilasEggsLevelUp()
	c.krallDesecrationLevelUp()
	c.aNestOfLepharistsLevelUp()
	c.sealingAbyssGateStart()
	c.swordTranscendenceLevelUp()
	c.barringTheGateLevelUp()
	c.aCharmedCubeLevelUp()
	c.teachingALessonLevelUp()
	c.hitThemWhereItHurtsLevelUp()
	c.wheresRaeThisTimeLevelUp()
	c.newSkillLevelUp(1205)
	c.newSkillLevelUp(2132)
	c.pearlOfProtectionLevelUp()
	c.levelUpStartQuests()
}
