package main

import (
	"fmt"
	"go/format"
	"io"
	"slices"
	"strings"
)

// GenTest writes game/quest_<id>_replay_test.go: the Java run's client actions replayed against the Go quest
// handlers (game/quest_replay_helpers_test.go), asserting the dialog windows, quest actions, movies and system
// messages the Java server sent. Only the last session of the log (from the last CM_ENTER_WORLD) is used, its
// starting quest state comes from that session's SM_QUEST_LIST. questItems are granted where the run looted them.
func GenTest(w io.Writer, questID int32, packets []Packet, source string, questItems []int32) error {
	packets = lastSession(packets)
	var initial []QuestAct
	for _, p := range packets {
		if !p.Client && p.Op == "SM_QUEST_LIST" {
			if started, ok := startedQuests(p.Body); ok {
				initial = started
			}
		}
	}
	steps := Timeline(packets, TimelineOptions{Loot: true})
	var body strings.Builder
	emitted := 0
	var ungranted []string
	for _, s := range steps {
		if s.Kind == "loot" && s.Item != 0 && !slices.Contains(questItems, s.Item) && !slices.Contains(ungranted, fmt.Sprint(s.Item)) {
			ungranted = append(ungranted, fmt.Sprint(s.Item))
		}
		if line, ok := s.testLine(questItems); ok {
			body.WriteString("\t\t" + line + "\n")
			emitted++
		} else if line != "" {
			body.WriteString("\t\t// " + line + "\n")
		}
	}
	if emitted == 0 {
		return fmt.Errorf("no replayable client action in %s", source)
	}
	note := ""
	if len(ungranted) > 0 {
		note = "\n// Looted but not granted (pass -items to grant quest items): " + strings.Join(ungranted, ", ") + "."
	}
	var start strings.Builder
	for _, q := range initial {
		if q.ID == questID {
			fmt.Fprintf(&start, ", replayQuest{ID: %d, Status: %q, Vars: %d}", q.ID, q.Status, q.Vars)
		}
	}
	var out strings.Builder
	fmt.Fprintf(&out, `package game

// Generated by: pktdiff -gen-test %[1]d %[2]s
// Java run of quest %[1]d recorded with the real 1.9 client: the last session of the log, %[3]d steps. Each step is a
// client action; Want is what the Java server answered. Regenerate rather than hand-edit the Want lists; add
// hand-written checks in a separate test.%[6]s

import "testing"

func TestQuest%[1]dJavaReplay(t *testing.T) {
	f := newReplayFixture(t, %[1]d%[4]s)
	f.run([]replayStep{
%[5]s	})
}
`, questID, source, emitted, start.String(), body.String(), note)
	formatted, err := format.Source([]byte(out.String()))
	if err != nil {
		return fmt.Errorf("generated code does not parse: %w\n%s", err, out.String())
	}
	_, err = w.Write(formatted)
	return err
}

// testLine renders the step as a replayStep literal. When it cannot be replayed it returns ("comment", false).
func (s Step) testLine(questItems []int32) (string, bool) {
	name := fmt.Sprintf("%q", s.Action)
	want := s.want()
	switch s.Kind {
	case "click":
		if s.NPC != 0 {
			return fmt.Sprintf("{Name: %s, Kind: \"click\", NPC: %d%s},", name, s.NPC, want), true
		}
	case "select":
		if s.NPC != 0 {
			return fmt.Sprintf("{Name: %s, Kind: \"select\", NPC: %d, Dialog: %d, Quest: %d%s},", name, s.NPC, s.Dialog, s.Quest, want), true
		}
	case "movie":
		return fmt.Sprintf("{Name: %s, Kind: \"movie\", Movie: %d%s},", name, s.Movie, want), true
	case "kill":
		if s.NPC != 0 && (len(s.Windows) > 0 || len(s.Quests) > 0 || len(s.Movies) > 0) {
			// Mob experience and loot messages are not part of the kill event, so only the quest effects are asserted.
			return fmt.Sprintf("{Name: %s, Kind: \"kill\", NPC: %d%s},", name, s.NPC, s.wantQuestOnly()), true
		}
		return "", false
	case "loot":
		if slices.Contains(questItems, s.Item) {
			return fmt.Sprintf("{Name: %s, Kind: \"give\", Item: %d, Count: %d},", name, s.Item, s.Count), true
		}
		return "", false
	}
	return "TODO not replayable: " + s.Action + effectsComment(s), false
}

func effectsComment(s Step) string {
	if len(s.Effects) == 0 {
		return ""
	}
	return " -> java: " + strings.Join(s.Effects, " ; ")
}

func (s Step) want() string {
	var parts []string
	if len(s.Windows) > 0 {
		var ws []string
		for _, w := range s.Windows {
			ws = append(ws, fmt.Sprintf("{%d, %d}", w[0], w[1]))
		}
		parts = append(parts, "Windows: [][2]int32{"+strings.Join(ws, ", ")+"}")
	}
	parts = append(parts, s.questParts()...)
	if len(s.Movies) > 0 {
		var ms []string
		for _, m := range s.Movies {
			ms = append(ms, fmt.Sprint(m))
		}
		parts = append(parts, "Movies: []uint16{"+strings.Join(ms, ", ")+"}")
	}
	if len(s.Messages) > 0 {
		var ms []string
		for _, m := range s.Messages {
			ms = append(ms, fmt.Sprint(m))
		}
		parts = append(parts, "Messages: []int32{"+strings.Join(ms, ", ")+"}")
	}
	return wantLiteral(parts)
}

func (s Step) wantQuestOnly() string { return wantLiteral(s.questParts()) }

func (s Step) questParts() []string {
	if len(s.Quests) == 0 {
		return nil
	}
	var qs []string
	for _, q := range s.Quests {
		qs = append(qs, fmt.Sprintf("{Action: %d, ID: %d, Status: %q, Vars: %d}", q.Action, q.ID, q.Status, q.Vars))
	}
	return []string{"Quests: []replayQuest{" + strings.Join(qs, ", ") + "}"}
}

func wantLiteral(parts []string) string {
	if len(parts) == 0 {
		return ""
	}
	return ", Want: replayWant{" + strings.Join(parts, ", ") + "}"
}
