// Package commands describes the server commands shown by the account website.
package commands

type Command struct{ Name, Syntax, Description, Example, Category string }

var Player = []Command{
	{"ping", "/ping", "Show your connection latency in the game client.", "/ping", "Connection"},
}

// Admin includes every command registered by Java's admincommands scripts.
var Admin = []Command{
	{"add", "//add [player] <item ID> [count]", "Give an item to yourself or an online player.", "//add 160010002 5", "Items"},
	{"adddrop", "//adddrop <NPC ID> <item ID> <min> <max> <chance 0-100>", "Save a drop rule and apply it immediately.", "//adddrop 210133 160010002 1 2 50", "Items"},
	{"addset", "//addset [player] <set ID>", "Give every part of an item set; requires enough inventory space.", "//addset 1", "Items"},
	{"addskill", "//addskill <skill ID> <level>", "Teach a skill to the selected player, or yourself.", "//addskill 1000 1", "Players"},
	{"addtitle", "//addtitle <title ID 1-50> [player]", "Grant a title; Asmodian titles use the faction offset automatically.", "//addtitle 1", "Players"},
	{"ai", "//ai info", "Inspect the selected NPC's AI state and pending work.", "//ai info", "World"},
	{"announce", "//announce <message>", "Send a server announcement to everyone online.", "//announce Welcome to Siel!", "Messages"},
	{"announcefaction", "//announcefaction <ely|asmo> <message>", "Announce to one faction.", "//announcefaction ely Welcome!", "Messages"},
	{"announcements", "//announcements list | add <ALL|ELYOS|ASMODIANS> <NORMAL|ANNOUNCE|ORANGE|YELLOW|SHOUT> <seconds> <message> | delete <ID>", "Manage persistent repeating announcements.", "//announcements add ALL ANNOUNCE 3600 Welcome!", "Messages"},
	{"appearance", "//appearance <size|voice|hair|face|deco|head_size|tattoo> <value> | reset", "Temporarily change the selected player's appearance, or your own. Size: 0-50; voice: 0-3; hair: 1-43; face: 1-24; deco: 1-18; head_size: 0-100; tattoo: 1-13. Reset restores this session's original appearance.", "//appearance size 1.2", "Players"},
	{"ban", "//ban <player> [account|ip|full] [minutes]", "Ban a player account, IP or both; zero minutes means permanent.", "//ban Bob account 60", "Moderation"},
	{"banip", "//banip <IP> [minutes]", "Ban an IP address.", "//banip 192.0.2.1 60", "Moderation"},
	{"bk", "//bk <add|del|tele|list> [name]", "Manage your saved teleport destinations.", "//bk add home", "Movement"},
	{"configure", "//configure <show|set> <admin|gs|custom> <property> [value]", "Inspect or change supported live Go settings or command permissions. Changes last until restart. Use the panel's Server options for persistent settings.", "//configure show admin COMMAND_SPAWN", "Server"},
	{"delete", "//delete", "Remove the selected ordinary NPC spawn; cannot delete owned summons.", "//delete", "World"},
	{"dye", "//dye <color name|RGB hex|no>", "Dye the selected player's equipment, or your own. Use no to clear dye.", "//dye true white", "Items"},
	{"fsc", "//fsc <opcode> <format> <values...>", "Send yourself a custom packet. Format letters: c byte, h short, d integer, q long, f float, e double, s string.", "//fsc 0x7c c 4", "Diagnostics"},
	{"gag", "//gag <player> [minutes]", "Prevent an online player from chatting; omit minutes for an indefinite gag.", "//gag Bob 5", "Moderation"},
	{"givemissingskills", "//givemissingskills", "Restore eligible auto-learned and previously learned skills for your class and level, including its base class.", "//givemissingskills", "Players"},
	{"goto", "//goto <town>", "Teleport to a named town, such as poeta, sanctum, ishalgen or pandaemonium.", "//goto sanctum", "Movement"},
	{"heal", "//heal", "Restore the selected creature's health and mana.", "//heal", "Players"},
	{"html", "//html reload | test <filename.html>", "Reload the welcome page or display an HTML file from the server's HTML data directory.", "//html reload", "Diagnostics"},
	{"info", "//info", "Show the selected NPC or player's template and location.", "//info", "Diagnostics"},
	{"invis", "//invis", "Toggle your GM invisibility.", "//invis", "Players"},
	{"invul", "//invul", "Toggle your immunity to damage.", "//invul", "Players"},
	{"kick", "//kick <player>", "Disconnect an online player.", "//kick Bob", "Moderation"},
	{"kill", "//kill", "Kill the selected creature.", "//kill", "Players"},
	{"kinah", "//kinah [player] <amount>", "Give Kinah to yourself or an online player.", "//kinah Bob 1000", "Items"},
	{"legion", "//legion <disband|setlevel|setpoints|setname> <legion> [value]", "Manage a legion; levels range from 1 to 5.", "//legion setlevel Guardians 3", "Players"},
	{"morph", "//morph <NPC ID|cancel>", "Transform the selected player, or yourself, into an NPC. Use cancel to reset.", "//morph 210133", "Players"},
	{"moveplayertoplayer", "//moveplayertoplayer <player> <destination player>", "Teleport one online player to another, including their instance.", "//moveplayertoplayer Bob Ann", "Movement"},
	{"moveto", "//moveto <world ID> <X> <Y> <Z>", "Teleport to map coordinates.", "//moveto 210010000 806 1242 119", "Movement"},
	{"movetome", "//movetome <player>", "Bring an online player to your location.", "//movetome Bob", "Movement"},
	{"movetonpc", "//movetonpc <NPC template ID>", "Teleport to an existing spawn of that NPC.", "//movetonpc 210133", "Movement"},
	{"movetoplayer", "//movetoplayer <player>", "Teleport to an online player's location.", "//movetoplayer Bob", "Movement"},
	{"notice", "//notice <message>", "Send an information notice to everyone online.", "//notice Maintenance is complete.", "Messages"},
	{"petition", "//petition [ID [delete|reply <message>]]", "List petitions, inspect one by ID, or delete or reply to it.", "//petition", "Moderation"},
	{"playerinfo", "//playerinfo <player> [loc|item|group|skill|legion]", "Inspect an online player's account, location and gameplay details.", "//playerinfo Bob loc", "Diagnostics"},
	{"promote", "//promote <player> <acceslevel|membership> <mask>", "Change an online player's account access level (0-3) or membership (0-1) through the login server.", "//promote Bob acceslevel 1", "Moderation"},
	{"quest", "//quest start <ID> | set <ID> <NONE|START|REWARD|COMPLETE|LOCKED> <var>", "Start or update a quest for the selected player, or yourself. Set requires an existing quest state.", "//quest start 1000", "Players"},
	{"raw", "//raw <name>", "Send yourself the hexadecimal packet from packets/name.txt.", "//raw example", "Diagnostics"},
	{"reload", "//reload <quest|skill|portal|spawn>", "Reload the selected static data. Use reload_spawn to apply refreshed spawn data to the world.", "//reload skill", "Server"},
	{"reload_spawn", "//reload_spawn", "Recreate ordinary NPC and gatherable spawns, preserving summons, rifts and kisks.", "//reload_spawn", "World"},
	{"remove", "//remove <player> <item ID> [count]", "Remove items from an online player's inventory.", "//remove Bob 160010002 1", "Items"},
	{"revoke", "//revoke <player> <acceslevel|membership>", "Reset an online player's access level or membership to zero.", "//revoke Bob acceslevel", "Moderation"},
	{"rez", "//rez", "Resurrect the selected player, or yourself.", "//rez", "Players"},
	{"rprison", "//rprison <player>", "Release an online player from prison.", "//rprison Bob", "Moderation"},
	{"save_spawn", "//save_spawn [all]", "Export added spawns, or all spawns, into static_data/spawns/new. Exports require administrator review before being installed as permanent static data.", "//save_spawn", "World"},
	{"send", "//send <mapping name>", "Send packets from packets/name.xml to the selected player, or yourself.", "//send demo", "Diagnostics"},
	{"set", "//set <class|exp|ap|level|title> <value>", "Update the selected player, or yourself. Class IDs use the client's numeric class order and require a level 9 base class.", "//set level 20", "Players"},
	{"siege", "//siege help | list | capture <ID> <elyos|asmos|balaur> [legion ID] | set <ID> <current state> [next state]", "Manage fortress ownership and vulnerability. Use help for state values.", "//siege list", "World"},
	{"spawn", "//spawn <NPC or gatherable template ID> [norespawn]", "Add a spawn at your position.", "//spawn 210133 norespawn", "World"},
	{"speed", "//speed <percent 0-200>", "Increase your movement and flight speed; zero restores base speed.", "//speed 100", "Players"},
	{"sprison", "//sprison <player> <minutes>", "Send an online player to prison.", "//sprison Bob 5", "Moderation"},
	{"sys", "//sys <info|memory|gc|cancel> | <restart|shutdown> <seconds> <announce interval>", "Inspect the runtime, collect garbage, schedule exit or cancel it. A container's restart policy determines whether an exited server starts again.", "//sys restart 60 15", "Server"},
	{"unban", "//unban <player> [account|ip|full]", "Remove an account or IP ban for a player.", "//unban Bob account", "Moderation"},
	{"unbanip", "//unbanip <IP>", "Remove an IP ban.", "//unbanip 192.0.2.1", "Moderation"},
	{"ungag", "//ungag <player>", "Restore an online player's ability to chat.", "//ungag Bob", "Moderation"},
	{"unstuck", "//unstuck", "Return to your bind location while alive.", "//unstuck", "Movement"},
	{"weather", "//weather <region> <value 0-8> | reset", "Override a region's weather, or restore automatic weather.", "//weather poeta 1", "World"},
	{"zone", "//zone [refresh]", "Show or refresh your current zone.", "//zone refresh", "World"},
}
